parameters:
  environment: ''
  displayName: '' 
  dependsOn: '' 
  confileFile: ''
  serviceConnection: ''
  scriptName: ''

stages:
- stage: ${{ parameters.environment }}
  displayName: ${{ parameters.displayName }}
  dependsOn: ${{ parameters.dependsOn }}
  condition: succeeded()
  jobs:  
  - deployment: release
    displayName: Release
    pool: 
      vmImage: 'ubuntu-latest'
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps: 
          - download: current
            artifact: cicd
          - task: AzureCLI@2
            displayName: Provision infrastructure
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              scriptType: 'bash'
              scriptLocation: 'scriptPath'
              scriptPath: $(Pipeline.Workspace)/cicd/provisioning/${{parameters.scriptName}} 
              arguments: ./${{parameters.confileFile}}
              workingDirectory: $(Pipeline.Workspace)/cicd/provisioning
              addSpnToEnvironment: true

