name: Setup infrastructure

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: run ls
        run: ls -alh $GITHUB_WORKSPACE
        shell: bash

      - name: Run deploy.sh
        run: $GITHUB_WORKSPACE/deploy.sh
        shell: sh
