name: Setup infrastructure

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Make shell scripts executable
        run: chmod 754 *.sh
        shell: sh

      - name: Run deploy.sh
        run: $GITHUB_WORKSPACE/deploy.sh ${{ secrets.OBJ_ID }}
        shell: sh
